# Generated by Django 5.2.1 on 2025-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delete_status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Confirmed'), (2, 'Processed'), (3, 'Delivered'), (4, 'Rejected'), (5, 'Payment Success'), (6, 'Payment Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
