# Generated by Django 5.2.1 on 2025-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delete_status_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='delete_status',
            field=models.IntegerField(choices=[(0, 'Live'), (0, 'Delete')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED')], default=1),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
